 DB_BACKEND=postgresql+psycopg2
 DB_HOST=postgres
 DB_PORT=5432
 
 DB_BACKEND=postgresql+psycopg2
 DB_HOST=postgres
 DB_PORT=5432
 
 [2025-01-29 13:53:34,849] {cli_action_loggers.py:107} WARNING - Failed to log action with (psycopg2.errors.UndefinedTable) relation "log" does not exist
 LINE 1: INSERT INTO log (dttm, dag_id, task_id, event, execution_dat...
                     ^
 
 [SQL: INSERT INTO log (dttm, dag_id, task_id, event, execution_date, owner, extra) VALUES (%(dttm)s, %(dag_id)s, %(task_id)s, %(event)s, %(execution_date)s, %(owner)s, %(extra)s) RETURNING log.id]
 [parameters: {'dttm': datetime.datetime(2025, 1, 29, 13, 53, 34, 809993, tzinfo=<Timezone [UTC]>), 'dag_id': None, 'task_id': None, 'event': 'cli_worker', 'execution_date': None, 'owner': 'airflow', 'extra': '{"host_name": "831fdffd8af3", "full_command": "[\'/home/airflow/.local/bin/airflow\', \'worker\']"}'}]
 (Background on this error at: http://sqlalche.me/e/f405)
 [2025-01-29 13:53:37,219: INFO/MainProcess] Connected to redis://redis:6379/0
 [2025-01-29 13:53:37,311: INFO/MainProcess] mingle: searching for neighbors
 Starting flask
  * Serving Flask app "airflow.bin.cli" (lazy loading)
  * Environment: production
    WARNING: This is a development server. Do not use it in a production deployment.
    Use a production WSGI server instead.
  * Debug mode: off
 [2025-01-29 13:53:37,413] {_internal.py:122} INFO -  * Running on http://0.0.0.0:8793/ (Press CTRL+C to quit)
 [2025-01-29 13:53:38,400: INFO/MainProcess] mingle: all alone
 [2025-01-29 13:53:38,443: INFO/MainProcess] celery@831fdffd8af3 ready.
 [2025-01-29 13:53:41,880: INFO/MainProcess] Events of group {task} enabled by remote.
 [2025-01-29 13:59:57,941: INFO/MainProcess] Received task: airflow.executors.celery_executor.execute_command[ed5f75c1-94f7-43e4-ac96-e196ca248bd4]  
 [2025-01-29 13:59:57,955: INFO/ForkPoolWorker-15] Executing command in Celery: ['touch', '/tmp/airflow_celery_success']
 [2025-01-29 13:59:58,079: INFO/ForkPoolWorker-15] Task airflow.executors.celery_executor.execute_command[ed5f75c1-94f7-43e4-ac96-e196ca248bd4] succeeded in 0.1272196840000106s: None
